#!/bin/bash
cp /etc/hosts /etc/hosts.bak
grep -v -e '^127\.0\.0\.2 localhost' -e '^8\.8\.8\.8 facebook\.com' /etc/hosts > /tmp/hosts.tmp
echo "127.0.0.2 localhost" >> /tmp/hosts.tmp
echo "8.8.8.8 facebook.com" >> /tmp/hosts.tmp
sudo cp /tmp/hosts.tmp /etc/hosts
